name: Sync to GitLab

on:
  push:
    branches: [ main ]  # Change to your default branch
  workflow_dispatch:    # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Get full history
    
    - name: Push to GitLab
      run: |
        git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/emailmelindamcghee-dot/devops-blog.git  
        git push gitlab --all
        git push gitlab --tags
