name: Sync to GitLab

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Push to GitLab
      run: |
        git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/frogcatchers/devops-blog.git        
        git fetch gitlab
        git merge gitlab/main --allow-unrelated-histories || echo "No conflicts"
        git push gitlab main
        git push gitlab --tags
